#!/bin/local/bin/python
"""
 Copyright (c) 2009,2010 Kuan-Chung Chiu <buganini@gmail.com>

 Permission to use, copy, modify, and distribute this software for any
 purpose with or without fee is hereby granted, provided that the above
 copyright notice and this permission notice appear in all copies.

 THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 WHATSOEVER RESULTING FROM LOSS OF MIND, USE, DATA OR PROFITS, WHETHER
 IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
 OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

"""

import os
import sys
import bsdconv

def usage():
	print sys.argv[0], "conversion [arguments] files..."
	print "Arguments:"
	print "--no-test: actually rename the files"

def proc(d):
	if(os.path.isdir(d)):
		for i in os.listdir(d):
			proc(os.path.join(d,i))
	path=os.path.dirname(d)
	name=os.path.basename(d)
	newname=bsdconv.conv(p,name)
	if newname!=name:
		os.chdir(path)
		print "%s| %s => %s" % (path, name, newname)
		if(test==False):
			os.rename(name,newname)


if len(sys.argv)<3:
	usage()
	sys.exit()

p=bsdconv.create(sys.argv[1])
if p==None:
        print bsdconv.error()
        sys.exit()

cwd=os.getcwd()
arg=1
test=True
for item in sys.argv[2:]:
	if(arg==1):
		if item=='--':
			arg=0
		elif item=='--no-test':
			test=False
		else:
			arg=0
	if(arg==0):
		proc(os.path.realpath(item))
		os.chdir(cwd)

if test:
	print "\nUse --no-test to actually rename the files"
bsdconv.destroy(p)
